### PR TITLE
Remotes rate limit

### LINKED ISSUE #210: install_github:  API rate limit exceeded
For version 2.0.0 `remotes::install_github` I am running into the following error versus the `devtools::install_github` which has no such error.

## remotes installing github package

```
> remotes::install_github('trinker/clustext')
Downloading GitHub repo trinker/clustext@master
Error: HTTP error 403.
  API rate limit exceeded for 151.181.86.126. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0
  Rate limit reset at: 2018-10-16 15:23:35 UTC
```

## devtools installing github package: no problems

````
> devtools::install_github('trinker/clustext')
Downloading GitHub repo trinker/clustext@master
from URL https://api.github.com/repos/trinker/clustext/zipball/master
Installing clustext
Installing 1 package: dynamicTreeCut
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/dynamicTreeCut_1.63-1.zip'
Content type 'application/zip' length 91925 bytes (89 KB)
downloaded 89 KB

package ‘dynamicTreeCut’ succ....[truncated but everything enstalled correctly].............
```

### PR DESCRIPTION
**Pull request by jimhester**
So this uses the same bundled PAT on CI systems as devtools and adds more instructions on what to do if you hit the error.

Fixes #210

### CODE REVIEW

File: tests/testthat/test-github.R [hunk 1]
```diff
@@ -55,3 +55,41 @@ test_that("github_DESCRIPTION", {
...
+test_that("github_error", {
+  mockery::stub(
+    github_error,
+    "curl::parse_headers_list",
+    list(`x-ratelimit-remaining` = 0, `x-ratelimit-reset` = "1539962178"))
+
+  # Test without the TRAVIS envvar set
+  withr::with_envvar(c(TRAVIS = NA), {
+    err <- github_error(list(headers = "", status_code = "304", content = charToRaw('{"message": "foobar"}')))
+    expect_equal(conditionMessage(err),
```
Comment (hadley) [inline tests/testthat/test-github.R]: I think this would be slightly cleaner if it used `expect_known_output(conditionMessage(err), print = TRUE, ...)` since it makes it more clear that it's a regression test. Otherwise, LGTM

Comment (jimhester) [reply tests/testthat/test-github.R]: Ok, good suggestion, I have done so
