### PR TITLE
Fixing untar on Windows

### LINKED ISSUE #171: tar.exe: Option --force-local is not supported
When I use `remotes::install_local(force = TRUE)`, because of "Skipping install of '...' from a local remote, the SHA1 (0.1.0-90) has not changed since last install." I get the error `tar.exe: Option --force-local is not supported`.
I use a Windows 10 system.

Here is the complete output after the "DONE" statement:

    * DONE (...)                                                                                                                                     
    tar.exe: Option --force-local is not supported                                                                                                            
    Usage:                                                                                                                                                    
      List:    tar.exe -tf <archive-filename>                                                                                                                 
      Extract: tar.exe -xf <archive-filename>                                                                                                                 
      Create:  tar.exe -cf <archive-filename> [filenames...]                                                                                                  
      Help:    tar.exe --help                                                                                                                                 
    Error in if (inherits(status, "try-error") || status != 0) { :                                                                                            
      missing value where TRUE/FALSE needed                                                                                                                   
    In addition: Warning message:                                                                                                                             
    In system(cmd, intern = TRUE) :                                                                                                                           
      running command 'tar.exe -ztf "C:\Users\Name\AppData\Local\Temp\RtmpScq6Pl\file2688718c77bb\..._0.1.0-9000.tar.gz" --force-local' had status 1

Do you have an idea?

### PR DESCRIPTION
**Pull request by gaborcsardi**
`utils::untar()` calls `system()` with `intern = TRUE`,
so we need to check for `attr(status, "status")` as well.
In addition we silence the first `try()`, and give an
explicit message about retrying instead. See also #151.

Closes #171.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
It seems like I cannot  suppress the output from `untar()`.  I'll try a different approach and call  `tar --help` first, and see  if `--force-local` is mentioned there.

**Comment by gaborcsardi** [comment]
@jimhester I think this is good now.

File: R/utils.R [hunk 1]
```diff
@@ -157,17 +157,31 @@ with_rprofile_user <- function(new, code) {
 
 untar <- function(tarfile, ...) {
   if (os_type() == "windows") {
-    status <- try(utils::untar(tarfile, extras = "--force-local", ...))
-    if(inherits(status, "try-error") || status != 0){
+    tarhelp <- system2("tar", "--help", stdout = TRUE, stderr = TRUE)
```
Comment (jimhester) [inline R/utils.R]: If `Sys.getenv("TAR")` is 'internal' we should probably just skip this completely. Also what does `system2()` do if there is no tar executable on the PATH?

OTOH `extras` is ignored if using the internal tar implementation IIRC, so maybe it is fine as is.

Comment (gaborcsardi) [reply R/utils.R]: Oh, yeah, `system2` needs to  be `tryCatch()`-ed. Thanks for catching this.

File: R/utils.R [hunk 2]
```diff
@@ -157,17 +157,31 @@ with_rprofile_user <- function(new, code) {
...
+    forcelocal <- any(grepl("--force-local", tarhelp))
+    if (forcelocal)  {
+      status <- try(
+        suppressWarnings(utils::untar(tarfile, extras = "--force-local", ...)),
+        silent = TRUE)
+      if (inherits(status, "try-error") ||
+          is_error_status(status) || is_error_status(attr(status, "status"))) {
+        message("External tar failed with `--force-local`, trying without")
         utils::untar(tarfile, ...)
```
Comment (jimhester) [inline R/utils.R]: There are three cases that all end with `utils::untar(tarfile, ...)`. So we should be able to rewrite the case that returns the status with an early return and have the rest of the cases fall through.

Comment (gaborcsardi) [reply R/utils.R]: I tried that but it was actually less readable than the current code. You cannot mark "not done  yet"  with `status =  NULL`, because maybe that's  a legit return value. Do you need a `done` variable, plus `status` ... anyway, I'll give it another try.

File: R/utils.R [hunk 3]
```diff
@@ -157,15 +157,31 @@ with_rprofile_user <- function(new, code) {
...
+      system2("tar", "--help", stdout = TRUE, stderr = TRUE),
+      error = function(x) "")
+
+    if (any(grepl("--force-local", tarhelp)))  {
+      status <- try(
+        suppressWarnings(utils::untar(tarfile, extras = "--force-local", ...)),
+        silent = TRUE)
+      if (! inherits(status, "try-error") &&
+          ! is_error_status(status) &&
+          !is_error_status(attr(status, "status"))) {
```
Comment (jimhester) [inline R/utils.R]: Could we just roll these all into `is_error_status()`?

**Comment by gaborcsardi** [comment]
Thanks!
